Use skindent and dkcheck instead of dkcheck so that Sukerujo and Dedukti don't need to have the exact same version.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -190,7 +190,7 @@ fi
 
 if [ $TOOLS_PREFIX_GIVEN != true ]
 then
-    DKWITNESS=`which skcheck`
+    DKWITNESS=`which dkcheck`
     DKDIR=`dirname $DKWITNESS`
     if [ "$DKDIR" != "" ] ;
     then
@@ -228,16 +228,66 @@ else
     DKDIR=$TOOLS_PREFIX
 fi
 
+if [ $TOOLS_PREFIX_GIVEN != true ]
+then
+    SKWITNESS=`which skindent`
+    SKDIR=`dirname $SKWITNESS`
+    if [ "$SKDIR" != "" ] ;
+    then
+        if [ $INTERACTIVE = true ]
+        then
+            echo $BOLDTAG"Sukerujo installation found in $SKDIR."$NORMALTAG
+            echo "Press enter to use default or specify another location."
+            read USER_INPUT
+            if [ "$USER_INPUT" != "" ] ;
+            then
+                SKDIR=$USER_INPUT
+            else
+                # Default path kept: trim it to just let the PATH acting.
+                SKDIR=""
+            fi
+        else
+            # Default path: trim it
+            SKDIR=""
+        fi
+    else
+        # No skindent command found and no explicit prefix given.
+        echo $BOLDTAG"Sukerujo installation not found."$NORMALTAG
+        echo "Specify the path where to find Sukerujo commands."
+        read USER_INPUT
+        SKDIR=$USER_INPUT
+        # Finally check that a director was entered by the user.
+        if [ "$SKDIR" = "" ] ;
+        then
+            echo "Error. Sukerujo not available. Install it first."
+            exit 1
+        fi
+    fi
+else
+    # Explicit tools prefix given, keep it blindly.
+    SKDIR=$TOOLS_PREFIX
+fi
+
 # If path to Dedukti is empty here, then ocaml was found but using the PATH.
 # So do not prefix it explicitly, letting PATH finding the commands.
 if [ "$DKDIR" != "" ] ;
 then
-    DKCHECK=$DKDIR/skcheck
-    DKDEP=$DKDIR/skdep
+    DKCHECK=$DKDIR/dkcheck
 else
-    DKCHECK=skcheck
-    DKDEP=skdep
+    DKCHECK=dkcheck
 fi
+
+# If path to Sukerujo is empty here, then ocaml was found but using the PATH.
+# So do not prefix it explicitly, letting PATH finding the commands.
+if [ "$SKDIR" != "" ] ;
+then
+    SKINDENT=$SKDIR/skindent
+    SKDEP=$SKDIR/skdep
+else
+    SKINDENT=skindent
+    SKDEP=skdep
+fi
+
 # #############################################################################
 # Generate the installation and configuration file containing tools vars.
 CONFIGURATION_VARS_FILE=.config_var
@@ -252,7 +302,8 @@ echo "CAMLDEP=$CAMLDEP" >> $CONFIGURATION_VARS_FILE
 echo "COQC=$COQC" >> $CONFIGURATION_VARS_FILE
 echo "COQDEP=$COQDEP" >> $CONFIGURATION_VARS_FILE
 echo "DKCHECK=$DKCHECK" >> $CONFIGURATION_VARS_FILE
-echo "DKDEP=$DKDEP" >> $CONFIGURATION_VARS_FILE
+echo "SKDEP=$SKDEP" >> $CONFIGURATION_VARS_FILE
+echo "SKINDENT=$SKINDENT" >> $CONFIGURATION_VARS_FILE
 echo "WARN_ERROR=a" >> $CONFIGURATION_VARS_FILE
 chmod a-w $CONFIGURATION_VARS_FILE
 
@@ -268,5 +319,6 @@ echo "  ocamldep = $CAMLDEP"
 echo "  coqc = $COQC"
 echo "  coqdep = $COQDEP"
 echo "  dkcheck = $DKCHECK"
-echo "  dkdep = $DKDEP"
+echo "  skdep = $SKDEP"
+echo "  skindent = $SKINDENT"
 echo "Done"
