[Install/Build] Missing check for git. Check for LaTeX added and docs are now *not* built if LaTeX is not present.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -482,6 +482,41 @@ fi
 
 
 # #############################################################################
+# Misc non mandatory tools.
+
+# Check if LaTeX is available.
+LATEX=""
+LATEX=`which latex`
+
+# Check if Hevea is available to convert docs into HTML.
+HEVEA=""
+HEVEA=`which hevea`
+
+# Find GIT. This is used to make the build-stamp to know what was the last
+# commit involved in the current build.
+echo "#!/bin/sh" > gitlastsha.sh
+echo "# Do not modify manually. This file is automatically generated" >> gitlastsha.sh
+echo "# and not stored in the repository." >> gitlastsha.sh
+GIT=`which git`
+# Check that git is installed.
+if [ "$GIT" != "" ] ;
+then
+    # Check that we are in a git repository.
+    git log > /dev/null
+    if [ "$?" = 0 ] ;
+    then
+        echo "git log -1 --format=\"%H\"" >> gitlastsha.sh
+    else
+        echo "echo git log not available" >> gitlastsha.sh
+    fi
+else
+    echo "echo git log not available" >> gitlastsha.sh
+fi
+chmod +x gitlastsha.sh
+
+
+
+# #############################################################################
 # Misc administrativia
 
 # If Coq version is < 8.3pl2, then we must call focalizec with the
@@ -546,7 +581,8 @@ echo "INSTALL_MAN_DIR=$INSTALL_MAN_DIR" >> $CONFIGURATION_VARS_FILE
 echo "INSTALL_DOC_DIR=$INSTALL_DOC_DIR" >> $CONFIGURATION_VARS_FILE
 echo "FOCALIZEC_COQ_COMPATIBILITY_OPTION=$FOCALIZEC_COQ_COMPATIBILITY_OPTION" >> $CONFIGURATION_VARS_FILE
 echo "SUDO=$SUDO" >> $CONFIGURATION_VARS_FILE
-echo "HEVEAFOUND=$HEVEAFOUND" >> $CONFIGURATION_VARS_FILE
+echo "HEVEA=$HEVEA" >> $CONFIGURATION_VARS_FILE
+echo "LATEX=$LATEX" >> $CONFIGURATION_VARS_FILE
 chmod a-w $CONFIGURATION_VARS_FILE
 
 
@@ -598,7 +634,13 @@ echo "  other documentation -> $INSTALL_DOC_DIR"
 echo "  git = $GIT  (not important if not available)"
 echo "  zenon libraries directory = $ZENON_LIB_DIR"
 echo "  Use sudo to install -> $SUDO"
-if [ "$HEVEAFOUND" != "" ] ;
+if [ "$LATEX" != "" ] ;
+then
+    echo "  LaTeX found, PDF docs will be generated."
+else
+    echo "  LaTeX NOT found, PDF docs won't be generated."
+fi
+if [ "$HEVEA" != "" ] ;
 then
     echo "  Hevea DVI to HTML utility found, HTML docs will be generated."
 else
